### ISSUE TITLE
Filtered resource list "Showing X of Y" text may be confused for paged navigation

### ISSUE THREAD

**Issue by jhung** [platform-coop-toolkit/coop-library#132]
**Is your feature request related to a problem? Please describe.**

When a resource list is filtered, the text "Showing X of Y" may be confusing as it can be interpreted as part of a paged navigation.

For example: "Showing 5 of 20" may be interpreted as there are 5 results showing, with 15 other results accessible via a pager navigation, which is not the intended meaning.

**Describe the solution you'd like**
Suggest changing the wording so that the intent is clear: "Filtered Y items, X result(s)", or "Showing X resources matching filter", or "Showing X filtered results".

**Comment by greatislander** [comment]
### Search

50 of 200 resources matched

Your search term: 'capitalism'

### Filter

50 of 200 resources matched

Your filters:

- Starting a co-op
- Platform cooperativism
- Governance

### Search & Filter

50 of 200 resources matched

Your search term: 'capitalism'

Your filters:

- Starting a co-op
- Platform cooperativism
- Governance

**Comment by cherylhjli** [comment]
looks good to me!
