### ISSUE TITLE
Date added and date published information not visible in resource list

### ISSUE THREAD

**Issue by jhung** [platform-coop-toolkit/coop-library#141]
**Describe the bug**
Date added and date published information is not visible in a resource list, even though it is possible to sort by these criteria. There's no way to visually verify sorting is correct.

**To Reproduce**
1. Go to 'Explore'
2. Click on 'Sort by date added'
3. Notice the order of resources change, but there's no way to see what the dates are.

**Expected behavior**
When sorting by dates, the dates should also appear in the resource list.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox
- Version 72.0.1

**Comment by cherylhjli** [comment]
How about something like this? 
<img width="475" alt="Screen Shot 2020-02-13 at 9 43 30 AM" src="https://user-images.githubusercontent.com/9353905/74446035-512f8480-4e45-11ea-9a1a-b72c8e784163.png">

**Comment by greatislander** [comment]
Works for me!
