### ISSUE TITLE
Saved Searches - Improve notification when maximum saved searches are reached

### ISSUE THREAD

**Issue by jhung** [platform-coop-toolkit/coop-library#205]
## Is your feature request related to a problem? Please describe.

It's not very clear when the maximum saved searches has been reached. The text indicating this limit is not obvious.

After saving 50th search:
![image](https://user-images.githubusercontent.com/564762/75711070-c0093c00-5c93-11ea-8901-a74c818c3bd2.png)

## Describe the solution you'd like
Create distinction for the maximum limit reached by using **strong** text, or by putting this string on a separate line

## Describe alternatives you've considered
Another option is to not use a green notification with a check-mark, but something to indicate caution (i.e. dark yellow with a "?"). 

Perhaps consider adding a warning when the 48th and 49th searches are saved, indicate that they are approaching the limit.

**Comment by greatislander** [comment]
Oops, committed and pushed the fix for this to dev. See https://github.com/platform-coop-toolkit/coop-library/commit/85656eece861b4bd259ff7be3e94e332cdd849e2.
