### ISSUE TITLE
Reduce vertical spacing on Browse All page between header and start of page content

### ISSUE THREAD

**Issue by dayotte** [platform-coop-toolkit/coop-library#230]
I recommend cutting the vertical space in half between the bottom of the header image and the start of the page content. Would also recommend doing same for vertical space between Filter / Sort by and the top of the cards, in mobile view. @cherylhjli what do you think?
![Image 2020-03-18 at 3 28 PM](https://user-images.githubusercontent.com/6207009/77013433-4cbb2780-692d-11ea-962c-cdb70a6432cd.jpg)
![Image 2020-03-18 at 3 29 PM](https://user-images.githubusercontent.com/6207009/77013436-4dec5480-692d-11ea-8d80-c8a9c3404ab2.jpg)

**Comment by cherylhjli** [comment]
> I recommend cutting the vertical space in half between the bottom of the header image and the start of the page content. Would also recommend doing same for vertical space between Filter / Sort by and the top of the cards, in mobile view. @cherylhjli what do you think?
> ![Image 2020-03-18 at 3 28 PM](https://user-images.githubusercontent.com/6207009/77013433-4cbb2780-692d-11ea-962c-cdb70a6432cd.jpg)
> ![Image 2020-03-18 at 3 29 PM](https://user-images.githubusercontent.com/6207009/77013436-4dec5480-692d-11ea-8d80-c8a9c3404ab2.jpg)

Sounds good to me!
