### ISSUE TITLE
Link back to PCC website

### ISSUE THREAD

**Issue by greatislander** [platform-coop-toolkit/coop-library#253]
## Is your feature request related to a problem? Please describe.

For consistency, we should use the double pinetree icon to link back to the Platform Cooperativism Consortium website.

## Describe the solution you'd like

We need to do this in a way that still provides a clear path back to the Resource Library home page within the primary navigation area.

## Describe alternatives you've considered

Not applicable.

## Additional context

Not applicable.

**Comment by cherylhjli** [comment]
Thinking of introducing a universal nav bar at the top of the resource library, as well as future projects (directory, tool library) when they launch. Each link will take you to their prospective websites. We'll also replace the double pine logo in the resource library with its own logo.

Desktop:
![Web 1366 – 5](https://user-images.githubusercontent.com/9353905/78585757-65ba4880-7808-11ea-9eaa-81bf24873c39.png)

Tablet:
![iPad – 13](https://user-images.githubusercontent.com/9353905/78585780-6d79ed00-7808-11ea-8c40-60d3da2dc92d.png)

Mobile:
![iPhone 5-SE – 19](https://user-images.githubusercontent.com/9353905/78585790-710d7400-7808-11ea-90da-7ba4d813e6a5.png)

@dayotte @greatislander @jhung @erictheise thoughts?

**Comment by cherylhjli** [comment]
Also note that for mobile, there's no space for this so it's just simply a link back to the PCC page.

**Comment by cherylhjli** [comment]
Still working on what this might look like on the PCC page itself.

**Comment by greatislander** [comment]
@dayotte @jhung @colinbdclark Let us know what you think of these designs.

**Comment by dayotte** [comment]
@greatislander noticed that the tablet and mobile view here seem to be using a different/older background image?

**Comment by dayotte** [comment]
@cherylhjli realised these are just mockups so I deleted my last comment. I think the universal nav as you've got it looks great. For mobile perhaps there is a way we could incorporate it into the menu?

**Comment by greatislander** [comment]
@dayotte I would avoid that as it would involved changing the page markup on mobile (on desktop, they are two separate menus, so combining them on mobile would change tab order and screen reader feedback, and would involve manipulating the page layout when the browser resizes, which I think it would be best to avoid if possible).

**Comment by dayotte** [comment]
ok @greatislander that sounds reasonable

**Comment by dayotte** [comment]
@cherylhjli @greatislander could we make the upper nav vertically expandable perhaps? maybe a bit much

**Comment by dayotte** [comment]
I think that's fine @greatislander @cherylhjli

**Comment by cherylhjli** [comment]
@dayotte for context, I did try the vertically expanding drop down menu:

![iPhone 5-SE – 17](https://user-images.githubusercontent.com/9353905/78606744-cf981980-782b-11ea-999f-385dc3f0d695.png)
![iPhone 5-SE – 18](https://user-images.githubusercontent.com/9353905/78606745-d030b000-782b-11ea-933a-0bd8b7ae278d.png)

However, as you can see, because the PCC always has to stay at the top, even if the resource library is selected it breaks the convention of the selected item always being at the top. If we put resource library at the top, then the double pines would not appear :(
